/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Problems */
        get: operations["list_problems_api_problems_get"];
        put?: never;
        /** Create Problem */
        post: operations["create_problem_api_problems_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze New Problem */
        post: operations["analyze_new_problem_api_problems_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Problem */
        get: operations["get_problem_api_problems__problem_id__get"];
        put?: never;
        post?: never;
        /** Delete Problem */
        delete: operations["delete_problem_api_problems__problem_id__delete"];
        options?: never;
        head?: never;
        /** Update Problem */
        patch: operations["update_problem_api_problems__problem_id__patch"];
        trace?: never;
    };
    "/api/problems/{problem_id}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Test */
        post: operations["create_test_api_problems__problem_id__tests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/tests/{test_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Test */
        delete: operations["delete_test_api_problems__problem_id__tests__test_id__delete"];
        options?: never;
        head?: never;
        /** Update Test */
        patch: operations["update_test_api_problems__problem_id__tests__test_id__patch"];
        trace?: never;
    };
    "/api/problems/{problem_id}/tests/expected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Expected */
        post: operations["compute_expected_api_problems__problem_id__tests_expected_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/drafts/{language}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_problems__problem_id__drafts__language__get"];
        /** Save Draft */
        put: operations["save_draft_api_problems__problem_id__drafts__language__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Execution Job */
        post: operations["create_execution_job_api_problems__problem_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submissions */
        get: operations["submissions_api_problems__problem_id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/ai/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Generation Job */
        post: operations["create_generation_job_api_problems__problem_id__ai_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generation-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Job */
        get: operations["get_generation_job_api_generation_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_problems__problem_id__ai_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat History */
        get: operations["chat_history_api_problems__problem_id__chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Usage */
        get: operations["ai_usage_api_ai_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIUsagePublic */
        AIUsagePublic: {
            /**
             * Operation
             * @enum {string}
             */
            operation: "analyze" | "generate" | "tutor";
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Text */
            text?: string | null;
            /** Image Base64 */
            image_base64?: string | null;
            /** Image Mime */
            image_mime?: ("image/png" | "image/jpeg" | "image/webp") | null;
        };
        /** ChatTurnPublic */
        ChatTurnPublic: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "hint" | "question" | "solution";
            /** User Message */
            user_message: string;
            /** Assistant Message */
            assistant_message: string;
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DraftPublic */
        DraftPublic: {
            /**
             * Language
             * @enum {string}
             */
            language: "python" | "cpp" | "java" | "javascript";
            /** Source */
            source: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DraftWrite */
        DraftWrite: {
            /** Source */
            source: string;
        };
        /** ExecutionSummary */
        ExecutionSummary: {
            /** Passed */
            passed: number;
            /** Total */
            total: number;
            /** All Passed */
            all_passed: boolean;
            /** Max Time Ms */
            max_time_ms: number;
            /** Max Memory Kb */
            max_memory_kb: number;
        };
        /** ExpectedCompute */
        ExpectedCompute: {
            /** Args */
            args: unknown[];
            /** Current Expected */
            current_expected?: unknown | null;
        };
        /** ExpectedResult */
        ExpectedResult: {
            /** Computed */
            computed: unknown;
            /** Matches Current */
            matches_current: boolean | null;
        };
        /** GenerationJobPublic */
        GenerationJobPublic: {
            /** Id */
            id: string;
            /** Problem Id */
            problem_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "interrupted";
            /** Test Revision */
            test_revision: number;
            summary?: components["schemas"]["GenerationSummary"] | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** GenerationRequest */
        GenerationRequest: {
            /**
             * Seed
             * @default 20260917
             */
            seed: number;
        };
        /** GenerationSummary */
        GenerationSummary: {
            /** Small Crosscheck Count */
            small_crosscheck_count: number;
            /** Hidden Count */
            hidden_count: number;
            /** Model */
            model: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthPublic */
        HealthPublic: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @constant
             */
            database: "ok";
            /** Runner Configured */
            runner_configured: boolean;
            /** Runner Available */
            runner_available: boolean;
            /** Ai Configured */
            ai_configured: boolean;
            /** Detail */
            detail: string;
        };
        /** HiddenResult */
        HiddenResult: {
            /** Id */
            id: string;
            /**
             * Visibility
             * @constant
             */
            visibility: "hidden";
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "wrong_answer" | "compile_error" | "runtime_error" | "time_limit" | "memory_limit" | "output_limit" | "system_error";
            /**
             * Time Ms
             * @default 0
             */
            time_ms: number;
            /**
             * Memory Kb
             * @default 0
             */
            memory_kb: number;
        };
        /** JobCreate */
        JobCreate: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "run" | "submit";
            /**
             * Language
             * @enum {string}
             */
            language: "python" | "cpp" | "java" | "javascript";
            /** Source */
            source: string;
        };
        /** JobPublic */
        JobPublic: {
            /** Id */
            id: string;
            /** Problem Id */
            problem_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "run" | "submit";
            /**
             * Language
             * @enum {string}
             */
            language: "python" | "cpp" | "java" | "javascript";
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "interrupted";
            /** Test Revision */
            test_revision: number;
            /** Results */
            results?: (components["schemas"]["VisibleResult"] | components["schemas"]["HiddenResult"])[];
            summary?: components["schemas"]["ExecutionSummary"] | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** Parameter */
        Parameter: {
            /** Name */
            name: string;
            type: components["schemas"]["TypeDescriptor"];
        };
        /** ProblemCreate */
        ProblemCreate: {
            /** Title */
            title: string;
            /**
             * Statement
             * @default
             */
            statement: string;
            /**
             * Example Explanation
             * @default
             */
            example_explanation: string;
            /** Constraints */
            constraints?: string[];
            signature: components["schemas"]["Signature"];
            /** Source Text */
            source_text?: string | null;
        };
        /** ProblemPublic */
        ProblemPublic: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "analyzed" | "generating" | "ready" | "needs_review";
            /** Test Revision */
            test_revision: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Statement */
            statement: string;
            /** Example Explanation */
            example_explanation: string;
            /** Constraints */
            constraints: string[];
            signature: components["schemas"]["Signature"];
            /** Templates */
            templates: {
                [key: string]: string;
            };
            /** Time Limit Ms */
            time_limit_ms: number;
            /** Memory Limit Mb */
            memory_limit_mb: number;
            /** Tests */
            tests: components["schemas"]["TestCasePublic"][];
            /** Latest Generation Job Id */
            latest_generation_job_id?: string | null;
            /** Generation Error */
            generation_error?: string | null;
        };
        /** ProblemSummary */
        ProblemSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "analyzed" | "generating" | "ready" | "needs_review";
            /** Test Revision */
            test_revision: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProblemUpdate */
        ProblemUpdate: {
            /** Title */
            title?: string;
            /** Statement */
            statement?: string;
            /** Example Explanation */
            example_explanation?: string;
            /** Constraints */
            constraints?: string[];
            signature?: components["schemas"]["Signature"];
            /** Time Limit Ms */
            time_limit_ms?: number;
            /** Memory Limit Mb */
            memory_limit_mb?: number;
        };
        /** Signature */
        Signature: {
            /** Parameters */
            parameters: components["schemas"]["Parameter"][];
            return_type: components["schemas"]["TypeDescriptor"];
        };
        /** TestCaseCreate */
        TestCaseCreate: {
            /**
             * Kind
             * @default user
             * @enum {string}
             */
            kind: "public" | "user";
            /** Args */
            args: unknown[];
            /** Expected */
            expected: unknown;
        };
        /** TestCasePublic */
        TestCasePublic: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "public" | "user";
            /** Position */
            position: number;
            /** Args */
            args: unknown[];
            /** Expected */
            expected: unknown;
            /** Suite Version */
            suite_version: number;
        };
        /** TestCaseUpdate */
        TestCaseUpdate: {
            /** Args */
            args?: unknown[] | null;
            /** Expected */
            expected?: unknown | null;
        };
        /** TutorRequest */
        TutorRequest: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "hint" | "question" | "solution";
            /** Message */
            message: string;
            /** Language */
            language?: ("python" | "cpp" | "java" | "javascript") | null;
            /** Source */
            source?: string | null;
        };
        /** TutorResponse */
        TutorResponse: {
            /** Content */
            content: string;
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /** TypeDescriptor */
        TypeDescriptor: {
            /**
             * Base
             * @enum {string}
             */
            base: "int" | "long" | "string" | "bool";
            /**
             * Dimensions
             * @enum {integer}
             */
            dimensions: 0 | 1 | 2;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisibleResult */
        VisibleResult: {
            /** Id */
            id: string;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "public" | "user";
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "wrong_answer" | "compile_error" | "runtime_error" | "time_limit" | "memory_limit" | "output_limit" | "system_error";
            /** Expected */
            expected?: unknown;
            /** Actual */
            actual?: unknown;
            /**
             * Stdout
             * @default
             */
            stdout: string;
            /**
             * Stderr
             * @default
             */
            stderr: string;
            /**
             * Time Ms
             * @default 0
             */
            time_ms: number;
            /**
             * Memory Kb
             * @default 0
             */
            memory_kb: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthPublic"];
                };
            };
        };
    };
    list_problems_api_problems_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemSummary"][];
                };
            };
        };
    };
    create_problem_api_problems_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_new_problem_api_problems_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_problem_api_problems__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_problem_api_problems__problem_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_problem_api_problems__problem_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProblemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_api_problems__problem_id__tests_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCasePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_api_problems__problem_id__tests__test_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
                test_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_api_problems__problem_id__tests__test_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
                test_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCasePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_expected_api_problems__problem_id__tests_expected_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedCompute"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpectedResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_problems__problem_id__drafts__language__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
                language: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_api_problems__problem_id__drafts__language__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
                language: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_execution_job_api_problems__problem_id__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submissions_api_problems__problem_id__submissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_job_api_problems__problem_id__ai_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_job_api_generation_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_problems__problem_id__ai_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_history_api_problems__problem_id__chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatTurnPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_usage_api_ai_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIUsagePublic"][];
                };
            };
        };
    };
}
