import { ArrowLeft, FlaskConical, Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, pollJob, type Problem, type Signature, type TestCase } from '../api/client';
import { StatusBadge } from '../components/StatusBadge';
import { parseJsonValue, typeLabel } from '../lib/domain';

export function EditProblemPage() {
  const { id = '' } = useParams(); const [problem, setProblem] = useState<Problem | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [generating, setGenerating] = useState(false);
  const [dirtyExamples, setDirtyExamples] = useState<Set<string>>(new Set());
  const routeIdRef = useRef(id);
  const load = async (routeId = id) => { try { const value = await api.problem(routeId); if (routeIdRef.current !== routeId) return; setProblem(value); if (value.status === 'generating' && value.latest_generation_job_id) void watch(value.latest_generation_job_id, routeId); } catch (e) { if (routeIdRef.current === routeId) setError((e as Error).message); } };
  useEffect(() => { routeIdRef.current = id; setProblem(null); setDirtyExamples(new Set()); setError(''); void load(id); return () => { if (routeIdRef.current === id) routeIdRef.current = ''; }; }, [id]);
  const watch = async (jobId: string, routeId = id) => { setGenerating(true); try { const result = await pollJob(() => api.generationJob(jobId)); if (routeIdRef.current !== routeId) return; if (result.status !== 'completed') setError(result.error || '테스트 준비가 중단됐습니다.'); await load(routeId); } catch (e) { if (routeIdRef.current === routeId) setError((e as Error).message); } finally { if (routeIdRef.current === routeId) setGenerating(false); } };
  if (!problem) return <PageState error={error} />;
  const change = <K extends keyof Problem>(key: K, value: Problem[K]) => setProblem({ ...problem, [key]: value });
  const save = async () => { setBusy(true); setError(''); try { const updated = await api.updateProblem(id, { title: problem.title, statement: problem.statement, constraints: problem.constraints.map((item) => item.trim()).filter(Boolean), signature: problem.signature, time_limit_ms: problem.time_limit_ms, memory_limit_mb: problem.memory_limit_mb }); setProblem(updated); return updated; } catch (e) { setError((e as Error).message); throw e; } finally { setBusy(false); } };
  const generate = async () => { setBusy(true); setError(''); try { await save(); const job = await api.generate(id); void watch(job.id); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const mutateTest = (test: TestCase) => setProblem({ ...problem, tests: problem.tests.map((item) => item.id === test.id ? test : item) });
  return <div className="page edit-page"><header className="editor-page-header"><Link to="/" className="back-link"><ArrowLeft /> 문제 목록</Link><div className="title-line"><div><span className="eyebrow">PROBLEM SETUP</span><h1>분석 결과 확인</h1></div><StatusBadge status={problem.status} /></div><p>함수 형태와 예제를 확인한 뒤 테스트를 준비하세요. 의미 있는 내용을 고치면 기존 생성 결과는 무효화됩니다.</p></header>
    {error && <div className="notice error">{error}</div>}{problem.generation_error && <div className="notice error">최근 준비 실패: {problem.generation_error}</div>}
    <div className="edit-grid"><div className="edit-main">
      <section className="surface form-section"><div className="section-heading"><span className="step">01</span><div><h2>문제 내용</h2><p>Markdown으로 작성할 수 있습니다.</p></div></div><label>문제 제목<input value={problem.title} onChange={(e) => change('title', e.target.value)} /></label><label>문제 설명<textarea rows={12} value={problem.statement} onChange={(e) => change('statement', e.target.value)} /></label><label>제한사항 <small>한 줄에 하나씩</small><textarea rows={5} value={problem.constraints.join('\n')} onChange={(e) => change('constraints', e.target.value.split('\n'))} /></label></section>
      <SignatureEditor value={problem.signature} onChange={(signature) => change('signature', signature)} />
      <section className="surface form-section"><div className="section-heading"><span className="step">03</span><div><h2>공개 예제</h2><p>인자는 매개변수 순서의 JSON 배열입니다. long은 따옴표로 감싸세요.</p></div></div>{problem.tests.filter((test) => test.kind === 'public').map((test, i) => <TestEditor key={test.id} test={test} index={i} onDirtyChange={(dirty) => setDirtyExamples((current) => { const next = new Set(current); if (dirty) next.add(test.id); else next.delete(test.id); return next; })} onSave={async (args, expected) => mutateTest(await api.updateTest(id, test.id, { args, expected }))} onDelete={async () => { setDirtyExamples((current) => { const next = new Set(current); next.delete(test.id); return next; }); await api.deleteTest(id, test.id); await load(); }} />)}
        {problem.tests.filter((test) => test.kind === 'public').length === 0 && <div className="notice warning">테스트 준비에는 공개 예제가 하나 이상 필요합니다. 아래에서 예제를 추가하세요.</div>}<NewTest onDirtyChange={(dirty) => setDirtyExamples((current) => { const next = new Set(current); if (dirty) next.add('__new__'); else next.delete('__new__'); return next; })} onCreate={async (args, expected) => { await api.createTest(id, { kind: 'public', args, expected }); await load(); }} label="예제 추가" />
      </section>
    </div><aside className="edit-side"><section className="surface sticky-card"><span className="eyebrow">READY CHECK</span><h2>테스트 준비</h2><ul><li>문제 설명과 제한사항 확인</li><li>함수 매개변수 순서 확인</li><li>공개 예제 반환값 확인</li></ul><div className="limit-grid"><label>시간 <div><input type="number" value={problem.time_limit_ms} onChange={(e) => change('time_limit_ms', Number(e.target.value))} /><span>ms</span></div></label><label>메모리 <div><input type="number" value={problem.memory_limit_mb} onChange={(e) => change('memory_limit_mb', Number(e.target.value))} /><span>MB</span></div></label></div>{dirtyExamples.size > 0 && <div className="notice warning">저장하지 않은 예제가 있습니다. 예제를 저장한 뒤 테스트를 준비하세요.</div>}<button className="button ghost wide" disabled={busy || generating} onClick={() => void save().catch(() => undefined)}><Save size={17} /> 변경사항 저장</button><button className="button primary wide" disabled={busy || generating || dirtyExamples.size > 0 || !problem.tests.some((test) => test.kind === 'public')} onClick={() => void generate()}><FlaskConical size={17} /> {generating ? '검증 중…' : problem.status === 'ready' ? '테스트 다시 준비' : '테스트 준비 시작'}</button>{problem.status === 'ready' && <Link className="button success wide" to={`/problems/${id}`}>풀이 화면 열기</Link>}</section></aside></div>
  </div>;
}

function SignatureEditor({ value, onChange }: { value: Signature; onChange: (value: Signature) => void }) {
  const setParam = (index: number, patch: Partial<Signature['parameters'][number]>) => onChange({ ...value, parameters: value.parameters.map((item, i) => i === index ? { ...item, ...patch } : item) });
  const typeSelect = (type: Signature['return_type'], update: (type: Signature['return_type']) => void) => <><select aria-label="기본 타입" value={type.base} onChange={(e) => update({ ...type, base: e.target.value as typeof type.base })}>{['int','long','string','bool'].map((base) => <option key={base}>{base}</option>)}</select><select aria-label="배열 차원" value={type.dimensions} onChange={(e) => update({ ...type, dimensions: Number(e.target.value) as 0|1|2 })}><option value={0}>단일 값</option><option value={1}>1차원 배열</option><option value={2}>2차원 배열</option></select></>;
  return <section className="surface form-section"><div className="section-heading"><span className="step">02</span><div><h2>함수 시그니처</h2><p>지원 타입: int, long, string, bool과 1·2차원 배열</p></div></div><div className="signature-table"><div className="signature-head"><span>매개변수</span><span>타입</span><span /></div>{value.parameters.map((param, index) => <div className="signature-row" key={index}><input aria-label={`매개변수 ${index + 1} 이름`} value={param.name} onChange={(e) => setParam(index, { name: e.target.value })} /><div className="type-pair">{typeSelect(param.type, (type) => setParam(index, { type }))}</div><button className="icon-button danger" aria-label="매개변수 삭제" disabled={value.parameters.length === 1} onClick={() => onChange({ ...value, parameters: value.parameters.filter((_, i) => i !== index) })}><Trash2 size={16} /></button></div>)}</div><button className="text-button" onClick={() => onChange({ ...value, parameters: [...value.parameters, { name: `arg${value.parameters.length + 1}`, type: { base: 'int', dimensions: 0 } }] })}><Plus size={16} /> 매개변수 추가</button><div className="return-row"><strong>반환 타입</strong><div className="type-pair">{typeSelect(value.return_type, (return_type) => onChange({ ...value, return_type }))}</div><span className="type-preview">{typeLabel(value.return_type)}</span></div></section>;
}

function TestEditor({ test, index, onSave, onDelete, onDirtyChange }: { test: TestCase; index: number; onSave: (args: unknown[], expected: unknown) => Promise<void>; onDelete: () => Promise<void>; onDirtyChange: (dirty: boolean) => void }) {
  const [args, setArgs] = useState(JSON.stringify(test.args)); const [expected, setExpected] = useState(JSON.stringify(test.expected)); const [state, setState] = useState('');
  const save = async () => { try { const parsed = parseJsonValue(args); if (!Array.isArray(parsed)) throw new Error('인자는 JSON 배열이어야 합니다.'); await onSave(parsed, parseJsonValue(expected)); setState('저장됨'); onDirtyChange(false); } catch (e) { setState((e as Error).message); } };
  return <div className="test-editor"><div className="test-title"><strong>예제 {index + 1}</strong><span>{state}</span><button className="icon-button danger" aria-label={`예제 ${index + 1} 삭제`} onClick={() => void onDelete()}><Trash2 size={16} /></button></div><div className="test-fields"><label>args<textarea value={args} onChange={(e) => { setArgs(e.target.value); setState('저장 필요'); onDirtyChange(true); }} /></label><label>expected<textarea value={expected} onChange={(e) => { setExpected(e.target.value); setState('저장 필요'); onDirtyChange(true); }} /></label></div><button className="button subtle" onClick={() => void save()}>예제 저장</button></div>;
}

export function NewTest({ onCreate, onDirtyChange, label = '사용자 테스트 추가' }: { onCreate: (args: unknown[], expected: unknown) => Promise<void>; onDirtyChange?: (dirty: boolean) => void; label?: string }) {
  const [open, setOpen] = useState(false); const [args, setArgs] = useState('[]'); const [expected, setExpected] = useState('null'); const [error, setError] = useState('');
  const create = async () => { try { const parsed = parseJsonValue(args); if (!Array.isArray(parsed)) throw new Error('인자는 JSON 배열이어야 합니다.'); await onCreate(parsed, parseJsonValue(expected)); setOpen(false); setArgs('[]'); setExpected('null'); onDirtyChange?.(false); } catch (e) { setError((e as Error).message); } };
  if (!open) return <button className="text-button" onClick={() => { setOpen(true); onDirtyChange?.(true); }}><Plus size={16} /> {label}</button>;
  return <div className="test-editor new"><div className="test-fields"><label>args<textarea value={args} onChange={(e) => setArgs(e.target.value)} /></label><label>expected<textarea value={expected} onChange={(e) => setExpected(e.target.value)} /></label></div>{error && <small className="field-error">{error}</small>}<div className="inline-actions"><button className="button subtle" onClick={() => { setOpen(false); onDirtyChange?.(false); }}>취소</button><button className="button primary" onClick={() => void create()}>추가</button></div></div>;
}
function PageState({ error }: { error: string }) { return <div className="page"><div className={error ? 'notice error' : 'empty'}>{error || '문제를 불러오는 중…'}</div></div>; }
